-- Find total customers by countries
select country, count(distinct customer_id) as customer_count from gold.dim_customers group by country order by customer_count desc

-- Find total customers by gender
select gender, count(distinct customer_id) as customer_count from gold.dim_customers group by gender order by customer_count desc

-- Find total products by category
select category, count(distinct product_id) as product_count from gold.dim_products group by category order by product_count desc

-- What is the average cost in each category?
select category, avg(cost) as avg_cost from gold.dim_products group by category order by avg_cost desc

-- What is the total revenue guarenteed for each category?
select 
    p.category,
    sum(s.sales_amount) as total_revenue
from gold.fact_sales s
left join gold.dim_products p
on s.product_key=p.product_key
group by p.category
ORDER by total_revenue DESC

-- Find total revenue generated by each customer
select 
    c.customer_key,
    c.first_name,
    c.last_name,
    sum(s.sales_amount) as total_revenue
from gold.fact_sales s
left join gold.dim_customers c
on s.customer_key=c.customer_key
group by c.customer_key, c.first_name, c.last_name
ORDER by total_revenue DESC

-- What is the distribution of sold items across countries?
select 
    c.country,
    sum(s.quantity) as sold_items
from gold.fact_sales s
left join gold.dim_customers c
on s.customer_key=c.customer_key
group by c.country
ORDER by sold_items DESC


